# Generated by Django 4.1.1 on 2022-11-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packmover', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='professional',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='user',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
