# Generated by Django 4.1.1 on 2022-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packmover', '0002_rename_professional_siteuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='shiftingdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
